#!/usr/bin/env bash

b="\e[1m"
d="\e[2m"
r="\e[0m"

main() {

    setup_shell() {
        current_shell=$(basename "$SHELL")

        if [ "$current_shell" = "zsh" ]; then
            FILE="$HOME/.zshrc"
            INIT='eval "$(starship init zsh)"'
        else
            FILE="$HOME/.bashrc"
            INIT='eval "$(starship init bash)"'
        fi

        if ! grep -q "starship init" "$FILE"; then
            echo "$INIT" >> "$FILE"
            echo -e "Reload shell to apply changes: $d exec $current_shell -l $r"
        fi
    }

    case "$1" in
        monoline|miniline|customline|pzhline)
            set_preset "$1"
            setup_shell
        ;;
        zsh|bash)
            set_shell "$1"
        ;;
        *)
            help
        ;;
    esac
}

set_preset() {
    mkdir -p ~/.config
    cp "preset/$1.toml" ~/.config/starship.toml
}

set_shell() {
    if [ ! -x "$PREFIX/bin/$1" ]; then
        echo "The shell $1 is not installed."
        echo -e "Install it by executing:$d apt install zsh $r"
        return 1
    fi

    chsh -s "$1"
    echo "Start a new session, then exit this session."
}

check_shell() {
    current=$(basename "$SHELL")

    if [ "$current" = "zsh" ]; then
        echo -e " - zsh $d [active] $r\n - bash"
    else
        echo -e " - zsh\n - bash $d [active] $r"
    fi
}

help() {
    echo "Usage:"
    echo "  ./set <preset>        # change presets"
    echo "  ./set <bash|zsh>      # change default shell"

    echo "Preset:"
    echo " - monoline	- pzhline (zsh)"
    echo " - miniline"
    echo " - customline"
    echo " - ghline"

    echo "Shell (current):"
    check_shell

    echo "Example:"
    echo " - ./set pzhline"
    echo " - ./set bash"
}

main "$@"
