format = """
$directory\
$git_branch\
$git_status \
${custom.git}\
${custom.nodejs}\
${custom.js}\
${custom.golang}\
${custom.shell}\
${custom.ruby}\
${custom.python}\
${custom.c}\
${custom.cpp}\
${custom.csharp}
$character"""

[directory]
home_symbol ="☰"
format = "[$path](bold underline fg:cyan)"
truncation_length = 2
truncation_symbol = "…/"

[character]
disabled = false
success_symbol = '[»](bold)'
error_symbol = '[»](bold fg:red)'

[git_branch]
format = '[  $branch ](fg:white dimmed underline)'

[git_status]
format = "[$all_status](underline dimmed)"
modified = "~"
staged = "+"
untracked = "?"
deleted = "x"
conflicted = "!"

[custom.git]
format = "[ ](202 dimmed)"
detect_folders = [".git", "git"]

[custom.nodejs]
format = '[󰎙 ](green dimmed)'
detect_folders = ['node_modules', "nodejs", "Nodejs"]

[custom.ruby]
format = "[ ](red dimmed)"
detect_extensions = ['rb']
detect_folders = ["ruby", "Ruby"]

[custom.python]
format = "[󰌠 ](21 dimmed)"
detect_extensions = ['py']
detect_folders = ["python", "Python"]

[custom.js]
format = "[ ](yellow dimmed)"
detect_extensions = ["js"]
detect_folders = ["javascript", "Javascript"]

[custom.shell]
format = "[ ](green dimmed)"
detect_extensions = ["sh"]
detect_folders = ["shell", "Shell"]

[custom.c]
format = "[󰙱 ](33 dimmed)"
detect_extensions = ["c"]

[custom.cpp]
format = "[󰙲 ](33 dimmed)"
detect_extensions = ['cpp']

[custom.csharp]
format = "[󰌛 ](199 dimmed)"
detect_extensions = ["cs"]

[custom.golang]
format = "[󰟓 ](cyan dimmed)"
detect_extensions = ["go"]
detect_folders = ["golang", "Golang"]
